[mcp_servers.chrome-devtools]
args = ["chrome-devtools-mcp@latest"]
command = "bunx"

[mcp_servers.context-mode]
args = [
    "-y",
    "context-mode",
]
command = "bunx"

[mcp_servers.context7]
url = "https://mcp.context7.com/mcp"

[mcp_servers.context7.http_headers]
Authorization = "Bearer ctx7sk-6779e259-4a32-4676-a43e-9d58519f6370"

[mcp_servers.figma]
url = "http://127.0.0.1:3845/mcp"

[mcp_servers.filesystem]
args = [
    "-y",
    "@modelcontextprotocol/server-filesystem",
    "/Users/robin.rehbein/Code/noah",
]
command = "bunx"

[mcp_servers.firecrawl-mcp]
args = [
    "-y",
    "firecrawl-mcp",
]
command = "npx"

[mcp_servers.firecrawl-mcp.env]
FIRECRAWL_API_KEY = "fc-4e759433486240e9a88e9e4f378ba815"

[mcp_servers.memory]
args = [
    "-y",
    "@modelcontextprotocol/server-memory",
]
command = "bunx"

[mcp_servers.morph-mcp]
args = [
    "-y",
    "@modelcontextprotocol/server-filesystem",
    "/Users/robin.rehbein/Code/noah",
]
command = "npx"

[mcp_servers.morph-mcp.env]
MORPH_API_KEY = "sk-QI2WvhHjAUGCCjERCbjXPH5psUVzDFugo0D-Af8ABPMXBJOk"

[mcp_servers.postgres]
args = [
    "-y",
    "@modelcontextprotocol/server-postgres",
    "postgresql://noah:noah123@localhost:5432/noah",
]
command = "bunx"

[mcp_servers.sequential-thinking]
args = [
    "-y",
    "@modelcontextprotocol/server-sequential-thinking",
]
command = "bunx"

[mcp_servers.z-ai-vision]
args = [
    "-y",
    "@z_ai/mcp-server",
]
command = "bunx"

[mcp_servers.z-ai-vision.env]
Z_AI_API_KEY = "9a5544abd1bd4ca982e6fe922e714dd1.ANxLk9NvT4tYG8Bo"
Z_AI_MODE = "ZAI"

[mcp_servers.z-ai-web-reader]
url = "https://api.z.ai/api/mcp/web_reader/mcp"

[mcp_servers.z-ai-web-reader.http_headers]
Authorization = "Bearer 9a5544abd1bd4ca982e6fe922e714dd1.ANxLk9NvT4tYG8Bo"

[mcp_servers.z-ai-web-search]
url = "https://api.z.ai/api/mcp/web_search_prime/mcp"

[mcp_servers.z-ai-web-search.http_headers]
Authorization = "Bearer 9a5544abd1bd4ca982e6fe922e714dd1.ANxLk9NvT4tYG8Bo"

[mcp_servers.z-ai-zread]
url = "https://api.z.ai/api/mcp/zread/mcp"

[mcp_servers.z-ai-zread.http_headers]
Authorization = "Bearer 9a5544abd1bd4ca982e6fe922e714dd1.ANxLk9NvT4tYG8Bo"
